export { crearDeck } from './crear-deck'
export { pedirCarta } from './pedir-carta'
export { valorCarta } from './valor-carta'
export { turnoComputadora } from './turno-cpu'
export { crearCartaHTML } from './crear-carta-html'